roles/azimuth/defaults/main.yml

Allow a list of CaaS projects to be provided in `azimuth_caas_awx_projects`, which is added to `azimuth_caas_awx_default_projects` to create the full list of CaaS AWX projects.

Add azimuth_caas_awx_projects var

---

roles/awx/defaults/main.yml
roles/azimuth/defaults/main.yml
roles/community_images/defaults/main.yml

- Uses the updated slurm app provided by https://github.com/stackhpc/caas-slurm-appliance/pull/10/.
- Uses the "fat" prebuild images produced by https://github.com/stackhpc/slurm_image_builder/

Use updated CaaS slurm appliance

---

roles/azimuth/defaults/main.yml
roles/community_images/defaults/main.yml

Removes rocky ssh keys baked in to previous image.

Change Slurm image to openhpc_221027_1557.qcow2.

---

roles/azimuth/defaults/main.yml

Update CaaS version to use https://github.com/stackhpc/caas-slurm-appliance/pull/11

Bump caas to image-based patch version

---

roles/community_images/defaults/main.yml

See https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.123

Bump slurm image to fix ohpc-base-compute and RL8.7

---

roles/azimuth/defaults/main.yml

Workstation: https://github.com/stackhpc/caas-workstation/pull/7
Slurm: https://github.com/stackhpc/caas-slurm-appliance/pull/21

Bump versions of workstation and slurm

---

roles/azimuth/defaults/main.yml
roles/community_images/defaults/main.yml

Update CaaS to https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.126

Bump slurm image for slurm app v1.126 to support containerised workloads

---

roles/azimuth_capi_operator/defaults/main.yml
roles/azimuth_capi_operator/tasks/main.yml
roles/capi_cluster/defaults/main.yml
roles/capi_cluster/tasks/main.yml
roles/community_images/defaults/main.yml
roles/community_images/tasks/export_community_images.yml
roles/community_images/tasks/upload_image.yml

Add support for populating community images from azimuth-images manifests.
Kubernetes templates are also now generated from the available Kubernetes images.

Add support for using azimuth-images manifests

---

roles/azimuth_caas_operator/defaults/main.yaml

Fixes failing checkout because https://github.com/stackhpc/caas-slurm-appliance/commit/cb0d7930c6ebf2fc8e21178b5a579b3e07cc726e no longer belongs to a branch.

Update caas-slurm git SHA to latest on main

---

.github/scripts/github-update-version
.github/scripts/helm-update-version
.github/workflows/update-dependencies.yml

This covers all dependencies that can be updated by checking a Helm repo or GitHub releases.
A couple of weird ones remain - Keycloak operator and Postgres operator. Postgres operator now has a Helm chart that we can move to, but it is stored in an OCI repo so would need different code to check the available tags (this is also subject to migrating from the existing kustomize-based install).

Add chores to update dependencies

---

roles/community_images/defaults/main.yml

Jammy images work, but have issues with Harbor that need to be investigated further (maybe down to differing containerd versions?). 
For now, we revert to focal images until the issues can be bottomed out.

Revert to focal images for Kubernetes

---

roles/infra/defaults/main.yml
roles/infra/templates/resources.tf.j2

On clouds where Neutron is configured to assign a default MTU of 9000 to internal networks and where the OVN Octavia driver is in use for load balancers, the MTU mismatch between these internal networks and a 1500 MTU external network can cause issues with the NGINX Ingress LB for HA Azimuths deployments. Specifically, we find that loading the Azimuth web UI hangs when trying to fetch a large `bundle.js` file, but the web page can be fetched successfully with curl (because that doesn't pull in all the JS). The simplest fix for this seems to be forcing the seed network to have an MTU of 1500. Other networks with 9000 MTU (e.g. `portal-internal` networks created in other projects) apparently don't cause issues so this is the only change needed.

Add config option for seed network MTU

---

roles/azimuth/defaults/main.yml

https://github.com/stackhpc/azimuth/pull/65
also removed trailing whitespaces:
`<stdin>:9: trailing whitespace.
#   Indicates if Cluster-as-a-Service should be enabled
<stdin>:18: trailing whitespace.
else {}
warning: 2 lines add whitespace errors.`

Remove admin role from application credential

---

playbooks/deploy_capi_mgmt.yml
playbooks/provision_capi_mgmt.yml
playbooks/provision_cluster.yml
roles/capi_cluster/defaults/main.yml
roles/capi_cluster/tasks/main.yml

Provides a reference setup for the new Magnum driver.

Add playbooks for deploying a CAPI management cluster only

---

roles/azimuth_caas_operator/defaults/main.yml
roles/community_images/defaults/main.yml

See https://github.com/stackhpc/caas-slurm-appliance/pull/42

Bump Slurm image to fix CVE-2023-41914

---

roles/azimuth_caas_operator/defaults/main.yml
roles/azimuth_capi_operator/defaults/main.yml
roles/azimuth_identity_operator/defaults/main.yml
roles/capi_cluster/defaults/main.yml
roles/community_images/defaults/main.yml
roles/infra/defaults/main.yml

Note that the azimuth-images tag appears to go backwards because pre-release tags that did not follow the pre-release convention have been removed.

Version bumps of StackHPC-authored components for release

---

roles/azimuth_caas_operator/defaults/main.yml

This has a smaller docker container, but importantly fixes to making the parsing of outputs more robust.

Update caas_operator to v0.5.0

---

playbooks/generate_tests.yml
roles/capi_cluster/defaults/main.yml
roles/capi_cluster/tasks/main.yml

This is mainly to be able to do throwaway HA deploys for CI without requiring a certain fixed IP to be free at all times.

Make ingress IP optional for HA cluster

---

roles/kube_prometheus_stack/defaults/main.yml

K3s doesn't have standalone versions of some Kubernetes components that are alerted on by the default kube-prometheus-stack Prometheus rules. Disabled these alerts if running on k3s.

Disable irrelevant prometheus alerts when not HA

---

roles/ingress_nginx/defaults/main.yml

Version 4.8.4 was revoked by the ingress-nginx project.

Revert ingress-nginx update

---

roles/azimuth_caas_operator/defaults/main.yml
roles/community_images/defaults/main.yml

See [v1.138](https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.138)

Update slurm appliance to v1.138

---

roles/harbor/defaults/main.yml

This reverts commit fd1baabbc817c0bcff6d7582074a37496bf4e773.
This is required until https://github.com/goharbor/harbor-helm/pull/1675 merges.

Revert harbor to 1.13.1

---

roles/azimuth_caas_operator/defaults/main.yml

Depends on https://github.com/stackhpc/azimuth-caas-operator/pull/84 and subsequent bump of CaaS operator image version.

Add configurable timeout to CaaS Slurm platforms

---

roles/clusterapi/defaults/main.yml

In particular, this allows us to enable the `MachineSetPreflightChecks` feature gate, which prevents worker nodes from being created or remediated when the control plane is not ready.

Support for toggling CAPI feature gates

---

playbooks/destroy.yml

This is for use in HA tests, so that the destroy always proceeds to the Terraform destroy of the seed even if something goes wrong with the deletion of the HA cluster. The Terraform destroy may still fail and will be reported as a step failure.

Add option to ignore errors during destroy

---

roles/azimuth_caas_operator/defaults/main.yml

Adds a new variable `azimuth_caas_stackhpc_slurm_appliance_home_manila_share`, defaulting to false, to control whether Slurm CaaS clusters use manila shares for home, independent of whether project manila shares are enabled.
It also automatically switches the ui-meta file between the versions for home on cinder to home on manila, which ensures labels aren't misleading and quota is correctly calculated.
This prevents dataloss in the situation where:
- Deploy default Azimuth without project shares
- Deploy a Slurm cluster - gets Cinder home
- Enable the project share support in Azimuth
- Patch the Slurm cluster - without this PR existing data in /home gets deleted
Note that setting this variable true **will** result in data in /home being lost when existing Slurm clusters are patched or …

Make whether slurm uses manila for home an explicit opt-in

---

roles/velero/defaults/main.yml

It seems that a recent Velero release bumped the image tag for the Velero operator from v.1.12.X to v1.13.0 and this causes our Velero Helm chart installation to fail as the operator enters a crash loop. Apparently the new operator expects a BackupStorageLocation called 'default' to exist (rather than just one with `spec.default: true`). This change fixes the issue for now and https://github.com/stackhpc/azimuth-config/pull/109 should help to catch installation issues like this sooner, until we add a full backup and restore CI test.

Fix velero install

---

roles/azimuth_capi_operator/defaults/main.yml
roles/community_images/defaults/main.yml

Python 3.9 is required for the `removeprefix()` method, whereas `regex_replace()` is shipped as part of ansible.builtin and works with Python 3.8.

Replace removeprefix with regex_replace

---

.github/workflows/test-pr.yml
roles/generate_tests/defaults/main.yml

The previous defaults were really for the Azimuth CI, and not really appropriate for general use. They have been moved into the CI config.

Generate tests for all platforms by default

---

roles/azimuth_caas_operator/defaults/main.yml
roles/community_images/defaults/main.yml

See https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.144 but note:
- RL8 and RL9 images now provided in community images. **RL9 is now the default**
- `azimuth` user now get sudo on all nodes and user's key is not injected into `rocky` user

Bump slurm to v1.144 with RL8 and RL9 images

---

roles/azimuth_caas_operator/defaults/main.yml
roles/community_images/defaults/main.yml

See https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.145

Bump slurm to v1.145 with RL9-OFED

---

playbooks/provision_cluster.yml

It can take a long time to upload images, and when a singlenode cluster has just been rolled over because of it's baseimage has changes, this means that k3s is down for the time that it takes to run community_images role

Upload community images after installing k3s

---

roles/clusterapi/defaults/main.yml

Issues seen during upgrade test, so rolling back until CAPI Helm charts move to `v1beta1` resources.

Roll back CAPO to v0.9.0

---

roles/azimuth_caas_operator/defaults/main.yml
roles/community_images/defaults/main.yml

- https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.147
- https://github.com/stackhpc/ansible-slurm-appliance/releases/tag/v1.146
Replaces https://github.com/stackhpc/ansible-collection-azimuth-ops/pull/531

Update slurm to v1.147: ohpcv3.1 etc

---

roles/azimuth_capi_operator/defaults/main.yml

Requires https://github.com/stackhpc/azimuth-charts/pull/14 to merge and a new azimuth-charts release to be cut before this PR will work.

Add Argo CD As default Azimuth app

---

roles/capi_cluster/defaults/main.yml

Kubernetes 1.29 is known to work in k3s setup.

Bump HA cluster Kubernetes version from 1.28 to 1.29

---

roles/postgres_operator/defaults/database.yml
roles/postgres_operator/defaults/main.yml

Fixes a mismatch between the pgbackrest client and server that causes WAL shipping to fail and storage usage to increase until the DB volume is full.

Fix broken WAL shipping for Keycloak DB

---

playbooks/provision_cluster.yml
roles/k9s/defaults/main.yml
roles/k9s/tasks/main.yml

~Draft: needs to be tested~ Tested and working in demo deployment

Install K9s on the seed

---

roles/generate_tests/defaults/main.yml

Also, switch the repo2docker test to use a simpler (and hence faster) example repo.

Update CaaS test timeout to reflect increased job timeout

---

.github/workflows/update-dependencies.yml
playbooks/deploy.yml
roles/coral_credits/defaults/main.yaml
roles/coral_credits/tasks/main.yaml

https://github.com/azimuth-cloud/azimuth-config/pull/158 config patch

Coral credits installation

---

roles/infra/defaults/main.yml

Tested upgrade to this image on a single-node and it works.

Bump infra image to Jammy 20241002 release

---

roles/azimuth_caas_operator/defaults/main.yml

Includes https://github.com/stackhpc/ansible-slurm-appliance/pull/457 which pulls in https://github.com/azimuth-cloud/ansible-collection-terraform/pull/16 to fix issue with waiting for connections on cluster

Bump slurm to v1.154

---

.gitignore
roles/azimuth_capi_operator/defaults/main.yml

As part of https://github.com/stackhpc/azimuth-llm/pull/51 the Azimuth app was moved into a separate wrapper chart (with backwards compatibility for now) so we need to update the default chart name in the app template too.

Update LLM app chart name

---

roles/clusterapi/defaults/main.yml

CAPO version 0.11.0 introduced a [regression](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2333) which causes OVN Octavia load balancers (e.g. those provisioned for ingress controllers and other services of type LoadBalancer) to stop working due to overly restrictive security groups. Until the issue is resolved we need cannot use any CAPO version after v0.10.5.

Revert CAPO to v0.10.5

---

roles/ingress_nginx/defaults/main.yml

Reverts azimuth-cloud/ansible-collection-azimuth-ops#729
This seems to have broken CaaS platform provisioning. Zenith subdomains for CaaS services do not work correctly and so platform provisioning times out. Need to investigate further.

Revert "Update ingress-nginx to 4.12.0"

---

roles/keycloak/tasks/main.yml

`keycloak_realm_users_req` is defined with status information even when skipped, previously leading to the non-existent `keycloak_realm_users_req.json` being referenced on repeat runs and failing. Now checks if json field is defined rather than entire object

Fixed Keycloak role failing on repeat runs

---

.github/workflows/test-pr.yml
playbooks/deploy.yml
playbooks/provision_cluster.yml
roles/flux/defaults/main.yml

Flux install on management cluster now dependent on `flux_enabled` variable. Configured here https://github.com/azimuth-cloud/azimuth-config/pull/219

Flux install now conditional on variable

---

roles/azimuth_caas_operator/defaults/main.yml
roles/community_images/defaults/main.yml

The `azimuth` user can no longer install packages on the cluster, as the dnf repofiles point to StackHPC's Ark Pulp mirror, (which is authenticated) and are disabled by default.

Bump Slurm to v1.159

---

roles/azimuth_caas_operator/defaults/main.yml

The `azimuth` user on Slurm platforms can be permitted to install dnf packages by providing credentials for StackHPC's Ark Pulp mirror:
1. [Create Ark credentials](https://github.com/stackhpc/stackhpc-release-train-clients/actions/workflows/create-client-credentials.yml) using the `stackhpc-dev` group, and by convention prefixing the client username with `caas-`.
2. Configure caas slurm platforms to use these via extravars:
```yaml
azimuth_caas_stackhpc_slurm_appliance_extra_vars_overrides:
dnf_repos_enabled: true
dnf_repos_username: $CLIENT_USERNAME
dnf_repos_password: "{{ vault_dnf_repos_password }}"
dnf_repos_allow_insecure_creds: true
```
3. Add the `vault_dnf_repos_password` value to `secrets.yml` in azimuth-config.
Note the variable …

Bump slurm to v1.160 to allow dnf installs

---

roles/certmanager/defaults/main.yml

By default, disable the use of Exact PathType in Ingress resources, to work around a bug in ingress-nginx [1].
[1] https://github.com/kubernetes/ingress-nginx/issues/11176

[CertManager] Disable the use of Exact PathType in Ingress resources

---

playbooks/deploy.yml

Currently backup and restore fails due to ordering issues with Crossplane CRD installations https://github.com/azimuth-cloud/azimuth-config/actions/runs/16367045671/job/46257272129#step:13:2056 . Needs fixing properly but disabling by default in CI to avoid blocking release for now

Make Crossplane dependent on OIDC being enabled

---

roles/azimuth_capi_operator/tasks/main.yml

Deploy 0.16.2 leads to the following error:
```
TASK [azimuth_cloud.azimuth_ops.azimuth_capi_operator : Apply ACL annotations to non-current templates] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: re.error: missing ), unterminated subpattern at position 0
fatal: [azimuth-cl2-seed]: FAILED! => {"msg": "Unexpected failure during module execution: missing ), unterminated subpattern at position 0", "stdout": ""}
```
It seems the regex negative lookahead isn't correctly formatted, this change fixes that

Fix regex expression in ansible changed_when field

---

roles/k3s/defaults/main.yml
roles/velero/tasks/restore.yml

A couple of fixes to ensure the backup + restore CI passes
- As the version of kubectl is based on the seed's k3s version, kubectl can become incompatible with the CAPI cluster if the two drift more than one minor version. Reverted k3s to v1.31.13 to amend this
- Added retry loop to backup check step in Velero role. Previously this could fail due to delays in the backup CRD being pulled from the S3 bucket
- Edited k3s defaults to ensure correct checksum is pulled regardless of its position in the upstream file

Fix backup CI failing from not finding Velero CRDs + revert k3s to 1.31.13

---

playbooks/download_images.yml

This is useful to let us download the images before an upgrade.

Add a playbook to download the community images
